name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Fetch submodules'
        run: git submodule update --init

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.67.0'
          extended: true

      - name: Build
        run: |
          git config --global core.quotePath false
          hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: ouuan/ouuan.github.io
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./public
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
